NO_BIN = ''
FOOD_CADY = 'f-'
BROWN_BIN = 'br-'
BLUE_BIN = 'b-'
GREY_BIN = 'gr-'
GREEN_BIN = 'g-'
PURPLE_LIDDED_BIN = 'p-'
GREEN_AND_GREY_BINS = 'ggr-'
GREEN_AND_BLUE_BINS = 'gb-'

ENCODED = {
    NO_BIN: 0,
    FOOD_CADY: 1,
    BROWN_BIN: 2,
    BLUE_BIN: 3,
    GREY_BIN: 4,
    GREEN_BIN: 5,
    PURPLE_LIDDED_BIN: 6,
    GREEN_AND_GREY_BINS: 7,
    GREEN_AND_BLUE_BINS: 8
}
